### ISSUE TITLE
[CRASH] Arri (MXF) Footage Crashes When Importing by Click Dragging into Timeline

### ISSUE THREAD

**Issue by Corruptinator** [sobotka/olive#31] opened 2020-04-04 01:13 UTC
**Specifications**
Windows 10 64 Bit, Ryzen 3900x, Nvidia RTX 2080 Super

**Summary**
I was testing out the two new Arri footage clips: **Alexa_XT_J001C012_140110_R6MS** (MOV), and the other **Alexa_Mini_LF_F003C003_190925_MN99** (MXF). when attempting to import the _Alexa_Mini_LF_F003C003_190925_MN99_ onto the timeline by click-dragging, the software crashes after the last 10 to 15 lines shown on Command Line:
```
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[DEBUG] Cache invalidated between 6 and 8 ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[DEBUG] Cache invalidated between 18 and 20 ((null):0)
[WARNING] Tried t[mxf @ 000001f83913aac0] o alEstimating duration from bitrate, this may be inaccurate
locate sample buffer with zero sample count ((null):0)
[DEBUG] Cache invalidated between 36 and 38 ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[DEBUG] Cache invalidated between 16 and 18 ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[DEBUG] Cache invalidated between 26 and 28 ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
```

**Additional Information / Output**
It could be a bitrate issue since its a different file format (MXF) but to replicate the issue, Import the footage: Alexa_Mini_LF_F003C003_190925_MN99 into Olive, and try to drag it onto the timeline, there the software should freeze up before crashing.

**Comment by sobotka** [comment] 2020-04-04 01:23
Duplicate of #29

**Comment by sobotka** [comment] 2020-04-04 04:15
Closing this in favour of the earlier report.

**Closed as completed by sobotka** 2020-04-04 04:15 UTC
Labels: Codec, Crash
