### ISSUE TITLE
[CRASH] Adding new Viewer node and connecting leads to segfault.

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#44] opened 2020-04-19 23:33 UTC
**Platform**
Debian Buster amd64

**Summary**
Adding a new Viewer node and connecting from a track yields a segfault.

**Additional Information / Output**
```
Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 4.19.0-8-amd64
System: Debian GNU/Linux 10 (buster) (debian 10)

./app/olive-editor(+0xc1d31)[0x55ed25987d31]
/lib/x86_64-linux-gnu/libc.so.6(+0x37840)[0x7f4e3f1a6840]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b)[0x7f4e3f1a67bb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x121)[0x7f4e3f191535]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x819a7)[0x7f4e3f6d49a7]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_Z11qt_assert_xPKcS0_S0_i+0x0)[0x7f4e3f6d3e29]
./app/olive-editor(+0x8a8f2)[0x55ed259508f2]
./app/olive-editor(+0x1136e3)[0x55ed259d96e3]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x8a3)[0x7f4e3f8e6933]
./app/olive-editor(+0x20d4a5)[0x55ed25ad34a5]
Signal: 6
```
```
Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 4.19.0-8-amd64
System: Debian GNU/Linux 10 (buster) (debian 10)

./app/olive-editor(+0xc1d31)[0x55ed25987d31]
/lib/x86_64-linux-gnu/libc.so.6(+0x37840)[0x7f4e3f1a6840]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b)[0x7f4e3f1a67bb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x121)[0x7f4e3f191535]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x819a7)[0x7f4e3f6d49a7]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_Z11qt_assert_xPKcS0_S0_i+0x0)[0x7f4e3f6d3e29]
./app/olive-editor(+0x8a8f2)[0x55ed259508f2]
./app/olive-editor(+0x1136e3)[0x55ed259d96e3]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x8a3)[0x7f4e3f8e6933]
./app/olive-editor(+0x20d4a5)[0x55ed25ad34a5]
Signal: 6
```

**Comment by itsmattkc** [comment] 2020-04-20 02:51
I believe this is a duplicate of #23

**Closed as completed by itsmattkc** 2020-04-20 02:51 UTC
Labels: Crash
