### ISSUE TITLE
[CRASH] Connecting nodes on track:block

### ISSUE THREAD

**Issue by ghost** [sobotka/olive#38] opened 2020-04-17 02:59 UTC
**Platform**
Manjaro 19.0.2 Cinnamon 64bit
Windows 10 64 bit
Olive 6df70802

**Summary**
Connect any node (Blur, Track, etc.) to a the `track` node's `block`. Crashes on both Linux and Windows 10.

**Additional Information / Output**

```
Starting program: /home/user/Applications/olive.AppImage 
[Detaching after fork from child process 3374]
[New LWP 3375]
[Detaching after vfork from child process 3377]
[Detaching after vfork from child process 3384]
[Detaching after fork from child process 3385]
[Detaching after vfork from child process 3386]
[Detaching after vfork from child process 3394]
[LWP 3375 exited]
process 3370 is executing new program: /run/user/1000/appimagelauncherfs/0000.AppImage
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 3396]
process 3370 is executing new program: /tmp/.mount_olive.HAGMUZ/local/bin/olive-editor
warning: Loadable section ".dynstr" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd55ae700 (LWP 3400)]
[New Thread 0x7fffd1ff7700 (LWP 3402)]
[New Thread 0x7fffd143e700 (LWP 3403)]
[New Thread 0x7fffd0c3d700 (LWP 3404)]
[New Thread 0x7fffcbfff700 (LWP 3405)]
[New Thread 0x7fffcb7fe700 (LWP 3406)]
[New Thread 0x7fffca0f3700 (LWP 3407)]
[New Thread 0x7fffc98f2700 (LWP 3408)]
[New Thread 0x7fffc90f1700 (LWP 3409)]
[New Thread 0x7fffc88f0700 (LWP 3410)]
[New Thread 0x7fffa7c59700 (LWP 3411)]
[Thread 0x7fffd143e700 (LWP 3403) exited]
[New Thread 0x7fffd143e700 (LWP 3425)]
[Thread 0x7fffd143e700 (LWP 3425) exited]
[New Thread 0x7fffd143e700 (LWP 3435)]
[New Thread 0x7fffa7458700 (LWP 3436)]
[New Thread 0x7fffa6c57700 (LWP 3437)]
[New Thread 0x7fffa6456700 (LWP 3438)]
[New Thread 0x7fffa5c55700 (LWP 3439)]
[New Thread 0x7fffa518e700 (LWP 3440)]
[New Thread 0x7fffa498d700 (LWP 3441)]
[New Thread 0x7fff97ffd700 (LWP 3442)]
[New Thread 0x7fff96ffb700 (LWP 3444)]
[New Thread 0x7fff977fc700 (LWP 3443)]
[New Thread 0x7fff967fa700 (LWP 3445)]
[New Thread 0x7fff95ff9700 (LWP 3446)]
[New Thread 0x7fff957f8700 (LWP 3447)]

Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x00000000004ce2b8 in olive::TrackOutput::BlockConnected(std::shared_ptr<olive::NodeEdge>) ()

   #0  0x00000000004ce2b8 in olive::TrackOutput::BlockConnected(std::shared_ptr<olive::NodeEdge>) ()
#1  0x00000000004ce8a0 in QtPrivate::QSlotObject<void (olive::TrackOutput::*)(std::shared_ptr<olive::NodeEdge>), QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#2  0x00007ffff2effb56 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Core.so.5
#3  0x00000000005cc232 in olive::NodeParam::EdgeAdded(std::shared_ptr<olive::NodeEdge>) ()
#4  0x00000000004f14f2 in olive::NodeParam::ConnectEdge(olive::NodeOutput*, olive::NodeInput*) ()
#5  0x0000000000568b90 in olive::NodeEdgeAddCommand::redo_internal() ()
#6  0x00000000005482c2 in olive::UndoCommand::redo() ()
#7  0x00007ffff3cbb37e in QUndoCommand::redo() ()
    at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#8  0x00007ffff3cbd693 in QUndoStack::push(QUndoCommand*) ()
    at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#9  0x0000000000565590 in olive::NodeViewItem::mouseReleaseEvent(QGraphicsSceneMouseEvent*) ()
#10 0x00007ffff3c344e8 in QGraphicsItem::sceneEvent(QEvent*) ()
    at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#11 0x00007ffff3c5863c in  ()
    at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#12 0x00007ffff3c5e1fa in QGraphicsScene::mouseReleaseEvent(QGraphicsSceneMouseEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#13 0x00007ffff3c694c0 in QGraphicsScene::event(QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#14 0x00007ffff394ec4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#15 0x00007ffff39562c7 in QApplication::notify(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#16 0x00007ffff2ed2ad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Core.so.5
#17 0x00007ffff3c8498c in QGraphicsView::mouseReleaseEvent(QMouseEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#18 0x00007ffff398ded8 in QWidget::event(QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff3a34a2e in QFrame::event(QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff3c8590b in QGraphicsView::viewportEvent(QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff2ed285d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Core.so.5
#22 0x00007ffff394ec25 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#23 0x00007ffff3956eeb in QApplication::notify(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#24 0x00007ffff2ed2ad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Core.so.5
#25 0x00007ffff395586f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#26 0x00007ffff39a822d in  () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#27 0x00007ffff39aac3b in  () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#28 0x00007ffff394ec4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#29 0x00007ffff39562c7 in QApplication::notify(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Widgets.so.5
#30 0x00007ffff2ed2ad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Core.so.5
#31 0x00007ffff3308ee5 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Gui.so.5
#32 0x00007ffff330ae55 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Gui.so.5
#33 0x00007ffff32e343b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Gui.so.5
#34 0x00007fffd3e0af4b in  () at /tmp/.mount_olive.HAGMUZ/local/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#35 0x00007ffff2ed0e6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Core.so.5
#36 0x00007ffff2ed9f74 in QCoreApplication::exec() () at /tmp/.mount_olive.HAGMUZ/local/bin/../lib/libQt5Core.so.5
#37 0x0000000000458909 in main ()
```

**Comment by itsmattkc** [comment] 2020-04-17 10:09
Duplicate of #23?

**Closed as completed** 2020-04-18 07:47 UTC
Labels: Crash
