### ISSUE TITLE
[CRASH] SegFault when playing with Node Editor. Unsure if the same as other crashes

### ISSUE THREAD

**Issue by DaniSeeh** [sobotka/olive#17] opened 2020-02-14 21:50 UTC
**Platform**
Build: 9de164c

System Details:
Manjaro Gnome (latest)
AMD Ryzen 1700x
NVIDIA GTX 1070
32gb RAM
**Summary**
I was playing around in the Node Editor. Honestly not sure what I did that caused it to crash. I was moving nodes around, reconnecting Inputs and Outputs. The very last thing I did before crashing was expand one of the Track nodes and it SegFaulted
**Additional Information / Output**
```
[daniel@daniel-pc app]$ gdb ./olive-editor
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./olive-editor...
(No debugging symbols found in ./olive-editor)
(gdb) run
Starting program: /home/daniel/Downloads/olive-9de164cfba8ac6384f7c87e5dab4d20a0bd26dfe/app/olive-editor 
/usr/lib/../share/gcc-9.2.0/python/libstdcxx/v6/xmethods.py:731: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  refcounts = ['_M_refcount']['_M_pi']
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffea72a700 (LWP 6291)]
qt5ct: using qt5ct plugin
[Detaching after fork from child process 6292]
[Detaching after fork from child process 6293]
Using Qt version: 5.14.0
[DEBUG] CONFIG: This is a 0.1.x config file, upconvert ((null):0)
[DEBUG]   CONFIG: Finding closest match to "29.97" ((null):0)
[DEBUG]   CONFIG: Closest match was 29.97 ((null):0)
[New Thread 0x7fffe98d2700 (LWP 6296)]
[New Thread 0x7fffe8fb4700 (LWP 6297)]
[New Thread 0x7fffe3fff700 (LWP 6298)]
[New Thread 0x7fffe37fe700 (LWP 6299)]
[New Thread 0x7fffe2ffd700 (LWP 6300)]
[New Thread 0x7fffe27fc700 (LWP 6301)]
[New Thread 0x7fffe1ffb700 (LWP 6302)]
[New Thread 0x7fffe17fa700 (LWP 6303)]
[New Thread 0x7fffe0ff9700 (LWP 6304)]
[New Thread 0x7fffb7fff700 (LWP 6305)]
[New Thread 0x7fffb77fe700 (LWP 6306)]
[New Thread 0x7fffb6ffd700 (LWP 6307)]
[New Thread 0x7fffb67fc700 (LWP 6308)]
[New Thread 0x7fffb5ffb700 (LWP 6309)]
[New Thread 0x7fffb57fa700 (LWP 6310)]
[New Thread 0x7fffb4ff9700 (LWP 6311)]
[New Thread 0x7fff9ffff700 (LWP 6312)]
[New Thread 0x7fff9f7fe700 (LWP 6313)]
[DEBUG] D-Bus global menu: no ((null):0)
[DEBUG] palette support is disabled ((null):0)
[DEBUG] custom style sheet is disabled ((null):0)
[New Thread 0x7fff8ffff700 (LWP 6314)]
[INFO] Setting output audio device to "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo" ((null):0)
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[Thread 0x7fffe98d2700 (LWP 6296) exited]
[New Thread 0x7fffe98d2700 (LWP 6315)]
[WARNING] Empty filename passed to function ((null):0)
[Thread 0x7fffe98d2700 (LWP 6315) exited]
[WARNING] Invalid params found: 0 0 -1 ((null):0)
[DEBUG] OpenGLBackend(0x555555b7f6d0) is waiting for 0 busy workers ((null):0)
[DEBUG] Cache invalidated between 0 and 0 ((null):0)
[New Thread 0x7fffe98d2700 (LWP 6317)]
[New Thread 0x7fff8e82b700 (LWP 6318)]
[New Thread 0x7fff8e02a700 (LWP 6319)]
[New Thread 0x7fff8d829700 (LWP 6320)]
[New Thread 0x7fff8d028700 (LWP 6321)]
[New Thread 0x7fff8c827700 (LWP 6322)]
[New Thread 0x7fff5ffff700 (LWP 6323)]
[New Thread 0x7fff67fff700 (LWP 6324)]
[New Thread 0x7fff677fe700 (LWP 6325)]
[New Thread 0x7fff66ffd700 (LWP 6326)]
[New Thread 0x7fff667fc700 (LWP 6327)]
[New Thread 0x7fff65ffb700 (LWP 6328)]
[New Thread 0x7fff657fa700 (LWP 6329)]
[New Thread 0x7fff64ff9700 (LWP 6330)]
[New Thread 0x7fff5f7fe700 (LWP 6331)]
[New Thread 0x7fff5effd700 (LWP 6332)]
[New Thread 0x7fff5e7fc700 (LWP 6333)]
[New Thread 0x7fff1f91d700 (LWP 6426)]
[Thread 0x7fff1f91d700 (LWP 6426) exited]
[WARNING] QXcbConnection: XCB error: 3 (BadWindow), sequence: 6969, resource id: 33554612, major code: 25 (SendEvent), minor code: 0 ((null):0)
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[New Thread 0x7fff1f91d700 (LWP 6427)]
[New Thread 0x7fff130e2700 (LWP 6428)]
[New Thread 0x7fff128e1700 (LWP 6429)]
[New Thread 0x7fff120e0700 (LWP 6430)]
[New Thread 0x7fff118df700 (LWP 6431)]
[New Thread 0x7fff110de700 (LWP 6432)]
[New Thread 0x7fff108dd700 (LWP 6433)]
[New Thread 0x7fff100dc700 (LWP 6434)]
[New Thread 0x7fff0f8db700 (LWP 6435)]
[New Thread 0x7fff0f0da700 (LWP 6436)]
[New Thread 0x7fff0e8d9700 (LWP 6437)]
[New Thread 0x7fff0e0d8700 (LWP 6438)]
[New Thread 0x7fff0d8d7700 (LWP 6439)]
[New Thread 0x7fff0d0d6700 (LWP 6440)]
[New Thread 0x7fff0c8d5700 (LWP 6441)]
[New Thread 0x7fff0c0d4700 (LWP 6442)]
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[DEBUG] Cache invalidated between 0 and 2 ((null):0)
[DEBUG] Cache invalidated between 0 and 10.15 ((null):0)
[DEBUG] Cache invalidated between 2 and 2.11667 ((null):0)
[DEBUG] Cache invalidated between 2.11667 and 4.11667 ((null):0)
[New Thread 0x7fff0b0d3700 (LWP 6443)]
[WARNING] Empty filename passed to function ((null):0)
[Thread 0x7fff0b0d3700 (LWP 6443) exited]
[New Thread 0x7fff0b0d3700 (LWP 6444)]
[WARNING] Failed to convert type 320 to string ((null):0)
[WARNING] Failed to convert type 8 to string ((null):0)
[WARNING] Failed to convert type 320 to string ((null):0)
[WARNING] Failed to convert type 8 to string ((null):0)
[WARNING] Failed to convert type 1536 to string ((null):0)
[WARNING] Failed to convert type 32 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 2 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 1536 to string ((null):0)
[WARNING] Failed to convert type 32 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 2 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 320 to string ((null):0)
[WARNING] Failed to convert type 8 to string ((null):0)
[WARNING] Failed to convert type 512 to string ((null):0)
[WARNING] Failed to convert type 512 to string ((null):0)
[WARNING] Failed to convert type 320 to string ((null):0)
[WARNING] Failed to convert type 1536 to string ((null):0)
[WARNING] Failed to convert type 32 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 2 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 4096 to string ((null):0)
[WARNING] Failed to convert type 320 to string ((null):0)
[WARNING] Failed to convert type 512 to string ((null):0)
[WARNING] Failed to convert type 1024 to string ((null):0)
[Thread 0x7fff0b0d3700 (LWP 6444) exited]

Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x00005555556ae06d in NodeViewItem::GetParameterConnectorRect(int) ()
(gdb) 
```

**Comment by itsmattkc** [comment] 2020-02-14 23:25
I believe this might be the same crash as #12 but will leave open as I'm not 100%

**Comment by itsmattkc** [comment] 2020-02-15 14:03
Based on the backtrace I believe this is a duplicate of #12. If it persists after that one's fixed, we'll re-open

**Closed as completed by itsmattkc** 2020-02-15 14:03 UTC
Labels: Crash, KNOWN
